"""empty message

Revision ID: 50e4ab658b0f
Revises: 2b82387b4449
Create Date: 2025-07-30 05:26:53.067968

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "50e4ab658b0f"
down_revision: Union[str, Sequence[str], None] = "2b82387b4449"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "configs",
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("uuid", sa.String(), nullable=True),
        sa.Column("config", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("server_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["server_id"],
            ["servers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("configs")
    # ### end Alembic commands ###
