"""empty message

Revision ID: bcef937727e3
Revises: 50e4ab658b0f
Create Date: 2025-07-30 05:36:24.910782

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bcef937727e3"
down_revision: Union[str, Sequence[str], None] = "50e4ab658b0f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "configs", sa.Column("user_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(
        None, "configs", "telegram_users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "configs", type_="foreignkey")
    op.drop_column("configs", "user_id")
    # ### end Alembic commands ###
