"""empty message

Revision ID: eb4f33bf713b
Revises: cf6a3f2257bf
Create Date: 2025-08-02 21:45:59.580827

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "eb4f33bf713b"
down_revision: Union[str, Sequence[str], None] = "cf6a3f2257bf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "telegram_users",
        sa.Column(
            "is_handle",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("telegram_users", "is_handle")
    # ### end Alembic commands ###
