"""empty message

Revision ID: 80df071c0863
Revises: 8890c269b1b7
Create Date: 2025-08-21 19:35:10.846226

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "80df071c0863"
down_revision: Union[str, Sequence[str], None] = "8890c269b1b7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subscriptions",
        sa.Column(
            "is_friend",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    op.add_column(
        "telegram_users",
        sa.Column(
            "is_friend",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("telegram_users", "is_friend")
    op.drop_column("subscriptions", "is_friend")
    # ### end Alembic commands ###
