"""empty message

Revision ID: 8890c269b1b7
Revises: b2ef4fa00a22
Create Date: 2025-08-17 11:04:27.913788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8890c269b1b7'
down_revision: Union[str, Sequence[str], None] = 'b2ef4fa00a22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('external_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'subscriptions', ['external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscriptions', type_='unique')
    op.drop_column('subscriptions', 'external_id')
    # ### end Alembic commands ###
