"""empty message

Revision ID: a714f70f674c
Revises: fea8323cde27
Create Date: 2025-07-30 15:10:37.429221

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a714f70f674c"
down_revision: Union[str, Sequence[str], None] = "fea8323cde27"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "telegram_users", sa.Column("referrer_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, "telegram_users", "telegram_users", ["referrer_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "telegram_users", type_="foreignkey")
    op.drop_column("telegram_users", "referrer_id")
    # ### end Alembic commands ###
