"""empty message

Revision ID: b2ef4fa00a22
Revises: 840e829b9262
Create Date: 2025-08-15 13:34:43.680313

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b2ef4fa00a22"
down_revision: Union[str, Sequence[str], None] = "840e829b9262"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "execute_products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("executor_name", sa.String(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("execute_products")
    # ### end Alembic commands ###
